### ISSUE TITLE
Abstimmungsfeature

### ISSUE THREAD

**Issue by AberDerBart** [AberDerBart/buelkbook#1]
Ein feature soll eingeführt werden, mit dem jeder für ein Motto abstimmen kann. Eine Liste von potenziellen Mottos soll dazu aus einer \n-getrennten textdatei gelesen werden - oder so ähnlich...

**Comment by tstehr** [comment]
- Ist es notwendig, den Fall zu unterstützen, dass während des Betriebs (also mit nicht leerem Datenbestand) die Abstimmungsoptionen geändert werden?
- Soll es eine Anzeige des aktuellen Standes der Abstimmung geben? 
- Hat jeder Eintrag einen Stimme, oder so viele Stimmen, wie er Personen repräsentiert?

**Comment by AberDerBart** [comment]
- es ist nicht notwendig, den Falll zu unterstützen, dass während des Betriebs (also mit nicht leerem Datenbestand) die Abstimmungsoptionen geändert werden.
- es soll eine Anzeige des aktuellen Standes der Abstimmung geben.
- Man soll so viele Stimmen haben, wie man Personen repräsentiert.
