### ISSUE TITLE
Die Darstellung der Anwesenheit zu den Mahlzeiten ist irritierend

### ISSUE THREAD

**Issue by AberDerBart** [AberDerBart/buelkbook#3]
Dadurch, dass die Tageszeit durch Komma getrennt ist und Morgen mit "Mo" abgekürzt ist, liest es sich intuitiv wie Montag (z.B. (Fr, Abd - So, Mo)). Ich würde vorschlagen, das Komma zu streichen und Morgen mit "Mor" abzukürzen.

**Comment by tstehr** [comment]
Dafür gibt es eine config in `data/meals.json`. Ich hab das in der Beispiel-Konfiguration mal entsprechend geändert, du kannst das dann einfach in diese Datei rüberkopieren oder dir auch ein komplett eigenes Format ausdenken
