### ISSUE TITLE
Bülkbook funktioniert nicht, Safari kann die Seite nicht öffnen.

### ISSUE THREAD

**Issue by AberDerBart** [AberDerBart/buelkbook#4]
Kam so von meinem Onkel 2. Grades...

**Comment by tstehr** [comment]
Hm, das ist so relativ schwer nachzuvollziehen. 

Ich bräuchte ein paar Details, wenn möglich:

- Benutztes Gerät und Betriebssystem (inkl Version)
- Benutzte Safari-Version
- Screenshot der angezeigten Fehlermeldung bzw der Webseite
- Beschreibung, was genau „nicht funktioniert“

**Comment by AberDerBart** [comment]
iPhone 6s, iOS 12.4.

**Comment by AberDerBart** [comment]
Ich habe das problem beheben können. Er hatte einen Link auf dem Startscreen (oder wie das heißt), der noch auf die alte URL verwiesen hat :D
